variables:
  COMMIT_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA-$CI_PIPELINE_ID"
  COMMIT_HASH: "$CI_COMMIT_SHA"

stages:
- build
- deploy
- stop


build:
  stage: build
  only:
    - main
    - master
  script:
    - build.sh $SCW_SECRET_KEY $CI_PROJECT_PATH


deploy_staging:
  stage: deploy
  only:
    - main
    - master
  environment:
    name: staging
    url: https://staging.URL_PROD
    on_stop: stop_staging
  script:
    - deploy.sh staging $SCW_SECRET_KEY $CI_PROJECT_PATH
  when: manual

stop_staging:
  stage: stop
  environment:
    name: staging
    action: stop
  script:
    - stop.sh staging $CI_PROJECT_PATH
  when: manual


deploy_prod:
  stage: deploy
  only:
    - main
    - master
  environment:
    name: prod
    url: https://URL_PROD
    on_stop: stop_prod
  script:
    - deploy.sh prod $SCW_SECRET_KEY $CI_PROJECT_PATH
  when: manual

stop_prod:
  stage: stop
  environment:
    name: prod
    action: stop
  script:
    - stop.sh prod $CI_PROJECT_PATH
  when: manual
