version: '3'

services:
  ms:
    build: .
    environment:
      HOST: "https://app.business-model-optimizer.com"
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - caddy_default
    volumes:
      - tmp:/tmp/
      - mongodata:/data
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/
      - tmp:/tmp/

volumes:
  mongodata:
    driver: anybox/buttervolume:latest
  tmp:

networks:
  caddy_default:
    external: true
