version: '3'

services:
  ms:
    build: .
    ports:
      - "8000:8000"
    environment:
      HOST: "business-model-optimizer.com"
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
